### ISSUE TITLE
Hostile language in comments

### ISSUE THREAD

**Issue by what-am-i-doing** [TheDeNuke/Divergences-of-Darkness-Rework-Public#15]
I was having a look through events and found gems like this:

# This removes cores on all territories that the Frankish Empire can claim that Burgundy also cannot claim. So have fun dealing with rebels you idiot.
(from MOD PBGFRKFlavor.txt)

# Failure to Restore Order on CFR - You had the badboy left over and you refused you actual idiot ###
(from MOD German Minors - 27000.txt)

It goes on like this but running a find-in-files search for the word "idiot" in events yields 32 hits across 21 files. Grow up.

**Comment by TheDeNuke** [comment]
**They are not for you.**

These comments are almost universally designed for me to make a point to the localization team that when the text for these events are written they are designed in a manner which notes the fact that the player had screwed up.

If you were to actually look at the localization keys attached to these events you would discover that almost all of them have the same messaging but in a less crude manner.

Additionally, while I'm coding these events I do not have the time to give complex descriptions of the events. I just need to give a quick message to localization regarding the type of language that has to be used in these events.

Thank You.
